{"uid":"6040ea37e3b65bf8","name":"test_select","fullName":"tests.integration.dbapi.sync.V2.test_queries#test_select","historyId":"3b3d23821752925431ccf78989e328ce","time":{"start":1718783732925,"stop":1718783732925,"duration":0},"description":"Select handles all data types properly.","descriptionHtml":"<p>Select handles all data types properly.</p>\n","status":"broken","statusMessage":"firebolt.utils.exception.OperationalError: Error executing query:\nDatabase 'integration_testing__1718783690531' does not exist or not authorized.","statusTrace":"engine_name = 'integration_testing__1718783690531'\ndatabase_name = 'integration_testing__1718783690531'\nauth = <firebolt.client.auth.client_credentials.ClientCredentials object at 0x7fe0f6fdca40>\naccount_name = 'automation', api_endpoint = 'api.staging.firebolt.io'\n\n    @fixture\n    def connection(\n        engine_name: str,\n        database_name: str,\n        auth: Auth,\n        account_name: str,\n        api_endpoint: str,\n    ) -> Connection:\n>       with connect(\n            engine_name=engine_name,\n            database=database_name,\n            auth=auth,\n            account_name=account_name,\n            api_endpoint=api_endpoint,\n        ) as connection:\n\ntests/integration/dbapi/sync/V2/conftest.py:21: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/firebolt/db/connection.py:57: in connect\n    return connect_v2(\n/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/firebolt/db/connection.py:138: in connect_v2\n    cursor.execute(f'USE DATABASE \"{database}\"')\n/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/firebolt/common/base_cursor.py:122: in inner\n    return func(self, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/firebolt/db/cursor.py:237: in execute\n    self._do_execute(query, params_list, skip_parsing)\n/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/firebolt/db/cursor.py:186: in _do_execute\n    self._raise_if_error(resp)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <firebolt.db.cursor.CursorV2 object at 0x7fe0f6c79e00>\nresp = <Response [500 Internal Server Error]>\n\n    def _raise_if_error(self, resp: Response) -> None:\n        \"\"\"Raise a proper error if any\"\"\"\n        if resp.status_code == codes.INTERNAL_SERVER_ERROR:\n>           raise OperationalError(\n                f\"Error executing query:\\n{resp.read().decode('utf-8')}\"\n            )\nE           firebolt.utils.exception.OperationalError: Error executing query:\nE           Database 'integration_testing__1718783690531' does not exist or not authorized.\n\n/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/firebolt/db/cursor.py:89: OperationalError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"service_secret","time":{"start":1718783731540,"stop":1718783731540,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"auth","time":{"start":1718783731540,"stop":1718783731706,"duration":166},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"service_id","time":{"start":1718783731540,"stop":1718783731540,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"api_endpoint","time":{"start":1718783731706,"stop":1718783731707,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"account_name","time":{"start":1718783731706,"stop":1718783731706,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"database_name","time":{"start":1718783732505,"stop":1718783732505,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"engine_name","time":{"start":1718783732505,"stop":1718783732505,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"connection","time":{"start":1718783732926,"stop":1718783733220,"duration":294},"status":"broken","statusMessage":"firebolt.utils.exception.OperationalError: Error executing query:\nDatabase 'integration_testing__1718783690531' does not exist or not authorized.\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1128, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/_pytest/fixtures.py\", line 900, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/tests/integration/dbapi/sync/V2/conftest.py\", line 21, in connection\n    with connect(\n  File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/firebolt/db/connection.py\", line 57, in connect\n    return connect_v2(\n  File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/firebolt/db/connection.py\", line 138, in connect_v2\n    cursor.execute(f'USE DATABASE \"{database}\"')\n  File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/firebolt/common/base_cursor.py\", line 122, in inner\n    return func(self, *args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/firebolt/db/cursor.py\", line 237, in execute\n    self._do_execute(query, params_list, skip_parsing)\n  File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/firebolt/db/cursor.py\", line 186, in _do_execute\n    self._raise_if_error(resp)\n  File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/firebolt/db/cursor.py\", line 89, in _raise_if_error\n    raise OperationalError(\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"afterStages":[],"labels":[{"name":"parentSuite","value":"tests.integration.dbapi.sync.V2"},{"name":"suite","value":"test_queries"},{"name":"host","value":"fv-az1382-384"},{"name":"thread","value":"2178-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.dbapi.sync.V2.test_queries"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"6040ea37e3b65bf8.json","parameterValues":[]}