{"uid":"ac9a1fb0e382d2e1","name":"test_account_no_user","fullName":"tests.integration.dbapi.async.V2.test_errors_async#test_account_no_user","historyId":"e1debb60b5d458094737f661dc1075c8","time":{"start":1733139514049,"stop":1733139515250,"duration":1201},"description":"Connection properly reacts to account that doesn't have\n    a user attached to it.","descriptionHtml":"<p>Connection properly reacts to account that doesn't have<br />\na user attached to it.</p>\n","status":"broken","statusMessage":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","statusTrace":"+ Exception Group Traceback (most recent call last):\n  |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_core/_run.py\", line 1039, in __aexit__\n  |     raise combined_error_from_nursery\n  | exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | Traceback (most recent call last):\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pytest_trio/plugin.py\", line 195, in _fixture_manager\n    |     yield nursery_fixture\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pytest_trio/plugin.py\", line 256, in run\n    |     self.fixture_value = await func_value.asend(None)\n    |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/tests/integration/dbapi/async/V2/conftest.py\", line 69, in connection_system_engine_no_db\n    |     async with await connect(\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/firebolt/async_db/connection.py\", line 140, in connect\n    |     return await connect_v2(\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/firebolt/async_db/connection.py\", line 196, in connect_v2\n    |     system_engine_url, system_engine_params = await _get_system_engine_url_and_params(\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/firebolt/async_db/util.py\", line 34, in _get_system_engine_url_and_params\n    |     response = await client.get(url=url)\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n    |     return await self.request(\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n    |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n    |     response = await self._send_handling_auth(\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1663, in _send_handling_auth\n    |     raise exc\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1652, in _send_handling_auth\n    |     next_request = await auth_flow.asend(response)\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/firebolt/client/auth/base.py\", line 174, in async_auth_flow\n    |     if self._lock.locked() and self._lock._owner_task == get_current_task():\n    | AttributeError: 'LockAdapter' object has no attribute '_owner_task'\n    +------------------------------------","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"database_name","time":{"start":1733139513779,"stop":1733139513779,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"account_name","time":{"start":1733139513780,"stop":1733139513780,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"api_endpoint","time":{"start":1733139513780,"stop":1733139513780,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"service_secret","time":{"start":1733139513780,"stop":1733139513780,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"service_id","time":{"start":1733139513780,"stop":1733139513780,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"auth","time":{"start":1733139513780,"stop":1733139514047,"duration":267},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"service_account_no_user","time":{"start":1733139514047,"stop":1733139514047,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"connection_system_engine_no_db","time":{"start":1733139514047,"stop":1733139514047,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"auth_no_user","time":{"start":1733139514047,"stop":1733139514047,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[],"labels":[{"name":"tag","value":"trio(run=<function run at 0x7f052a244b80>)"},{"name":"parentSuite","value":"tests.integration.dbapi.async.V2"},{"name":"suite","value":"test_errors_async"},{"name":"host","value":"fv-az1776-739"},{"name":"thread","value":"2113-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.dbapi.async.V2.test_errors_async"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["trio(run=<function run at 0x7f052a244b80>)"]},"source":"ac9a1fb0e382d2e1.json","parameterValues":[]}